WORKFLOW = {
    "order": 3,
    "workflow_type": "product_video",
    "label": "产品视频 / 商品演示",
    "aliases": ["product", "商品演示", "产品视频"],
    "template_kind": "linear",
    "title": "产品视频工作流",
    "nodes": [
        (
            "product_input",
            "textAnnotationNode",
            "产品输入",
            "产品图、功能、卖点和使用场景。",
            "input",
        ),
        (
            "feature_breakdown",
            "textAnnotationNode",
            "功能拆解",
            "拆解核心功能、使用步骤和演示重点。",
            "story",
        ),
        ("demo_script", "textAnnotationNode", "演示脚本", "讲解词、字幕和镜头顺序。", "script"),
        ("demo_frame", "imageGenNode", "演示关键画面", "生成产品演示关键帧。", "image"),
        ("demo_video", "videoNode", "演示视频片段", "生成产品演示视频片段。", "video"),
        ("voiceover_text", "textAnnotationNode", "讲解文案", "产品讲解配音文本。", "audio"),
        ("voiceover", "audioNode", "讲解音频", "由上游讲解文案生成配音。", "audio"),
        ("compose", "videoComposeNode", "成片合成", "合成视频、配音、字幕。", "compose"),
    ],
    "edges": [
        ("product_input", "feature_breakdown"),
        ("feature_breakdown", "demo_script"),
        ("demo_script", "demo_frame"),
        ("demo_frame", "demo_video"),
        ("demo_script", "voiceover_text"),
        ("voiceover_text", "voiceover"),
        ("demo_video", "compose"),
        ("voiceover", "compose"),
    ],
}
